const CATALOG = {
  ADD_PRODUCT: "CATALOG:ADD_PRODUCT",
  EDIT_PRODUCT: "CATALOG:EDIT_PRODUCT",
  REMOVE_PRODUCT: "CATALOG:REMOVE_PRODUCT",
  ADD_CATEGORY: "CATALOG:ADD_CATEGORY",
  EDIT_CATEGORY: "CATALOG:REMOVE_CATEGORY",
  REMOVE_CATEGORY: "CATALOG:REMOVE_CATEGORY"
};

export default CATALOG;
