const CATALOG = {
  ADD_PRODUCT_INIT: "CATALOG:ADD_PRODUCT_INIT",
  ADD_PRODUCT_ERROR: "CATALOG:ADD_PRODUCT_ERROR",
  ADD_PRODUCT: "CATALOG:ADD_PRODUCT",
  EDIT_PRODUCT: "CATALOG:EDIT_PRODUCT",
  REMOVE_PRODUCT: "CATALOG:REMOVE_PRODUCT",
  GET_PRODUCTS: "CATALOG:GET_PRODUCTS",
  ADD_CATEGORY: "CATALOG:ADD_CATEGORY",
  EDIT_CATEGORY: "CATALOG:REMOVE_CATEGORY",
  REMOVE_CATEGORY: "CATALOG:REMOVE_CATEGORY",
  ON_FILE_LOADED: "CATALOG:ON_FILE_LOADED",
  ON_FILE_SAVED: "CATALOG:ON_FILE_SAVED",
  ON_FILE_CLEAR: "CATALOG:ON_FILE_CLEAR",
  ADD_COLOR: "CATALOG:ADD_COLOR",
  EDIT_COLOR: "CATALOG:EDIT_COLOR",
  REMOVE_COLOR: "CATALOG:REMOVE_COLOR"
};

export default CATALOG;
